apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: ollama
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.1"
      requests:
        memory: "64Mi"
        cpu: "0.05"